### PR TITLE
Fix: Schedule is suggesting a time that conflicts with the existing schedule

### LINKED ISSUE #225: Schedule is suggesting a time that conflicts with the existing schedule

### PR DESCRIPTION
**Pull request by tysg**
Closes #225 

Also,
* Add test case to cover the scenario
* Extend the working hours to 9PM. Now drivers works from 9AM to 9PM.

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Schedule.java [hunk 1]
```diff
@@ -99,7 +99,17 @@ public void add(EventTime eventTime) throws SchedulingException {
...
 
-        NavigableSet<EventTime> candidates = schedule.subSet(now, true, lastCandidate, true);
+        // this should always be non null, since an event starting at midnight will always be the smallest
+        EventTime firstCandidate = schedule.lower(now);
+
+        if (!firstCandidate.overlaps(now)) {
+            firstCandidate = now;
+        } else {
+            schedule.remove(now);
+        }
```
Comment (junnbang) [inline src/main/java/seedu/address/model/person/Schedule.java]: to compare in treeset, theres no need to add the now into the schedule. when you use schedule.lower(now), it will return you the previous eventTime even if u didn't add the now into the schedule

**Review by junnbang — COMMENTED** [review]
looks fine, just minor changes

**Review by junnbang — APPROVED** [review]
looks fine
