### PR TITLE
Fix tasks card: should display event time instead of the full schedule

### LINKED ISSUE #211: UI - Task displays the driver's full schedule instead of the event time
Screenshot 2019-11-05 at 4 36 18 PM

### PR DESCRIPTION
**Pull request by tysg**
Closes #211

Now,
Screenshot 2019-11-06 at 4 10 08 PM

### CODE REVIEW

File: src/main/java/seedu/address/ui/TaskCard.java [hunk 1]
```diff
@@ -50,9 +51,9 @@ public TaskCard(Task task, int displayedIndex) {
         id.setText(displayedIndex + ". ");
         description.setText(task.getDescription().value);
         taskId.setText("Task ID: #" + task.getId());
-        assigned.setText("Assigned: " + task.getDriver().get().getSchedule() + " @ "
-            + task.getDriver().get().getName().fullName + " (#" + task.getDriver().get().getId()
-            + ") - " + task.getDriver().get().getPhone());
+        assigned.setText("Assigned: " + task.getEventTime().map(EventTime::toString).orElse("NOT ALLOCATED") + " @ "
+                + task.getDriver().get().getName().fullName + " (#" + task.getDriver().get().getId()
+                + ") - " + task.getDriver().get().getPhone());
```
Comment (junnbang) [inline src/main/java/seedu/address/ui/TaskCard.java]: i think using map here is redundant cos it will automatically change to a string when u concatenate.

so task.getEventTime().orElse("NOT ALLOCATED") will do

**Review by junnbang — APPROVED** [review]
just a minor change

File: src/main/java/seedu/address/ui/TaskCard.java (hunk 1 above)
Comment (tysng) [reply src/main/java/seedu/address/ui/TaskCard.java]: Nah, we are working with optionals here. I tried but couldn't compile, because `task.getEventTime()` returns an `Optional<EventTime>`. Then the type of the element inside`orElse` has to be `EventTime`
